version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: linkly-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkly_dev
    ports:
      - "5432:5432"