version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: linkly-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkly_dev
    ports:
      - "5432:5432"
  app:
    image: linkly/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    entrypoint: ["/bin/sh", "-c", "/app/entrypoint.sh"]
